-- 1. Definir el contexto en el que realizaré mi Trabajo Final
USE WAREHOUSE CHEETAH_WH;
USE ROLE TRAINING_ROLE;
USE DATABASE CHEETAH_DB;
USE SCHEMA FT_SCHEMA;

-- 2. Crear las tablas con sus tipos de datos correspondientes
-- Crear formato necesario
CREATE OR REPLACE FILE FORMAT mi_formato_csv
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  TIMESTAMP_FORMAT = 'DD/MM/YYYY HH24:MI'; -- Ajustar el formato real del texto


-- Crear las tablas

CREATE OR REPLACE TABLE Orders (
    order_id VARCHAR(28),
    created_at DATETIME,
    status VARCHAR(255),
    amount NUMBER(10,2),
    merchant_id VARCHAR(28),
    COUNTRY VARCHAR(255)
);

CREATE OR REPLACE TABLE Refunds (
    order_id VARCHAR(28),
    refunded_at DATETIME,
    amount NUMBER(10,2)
);

CREATE OR REPLACE TABLE Merchants (
    merchant_id VARCHAR(28),
    name VARCHAR(255)
);


;

-- 3. Ejercicios SQL



-- 3.1 Ejercicio 1
SELECT 
COUNTRY AS PAISES, STATUS AS ESTADO_DE_OPERACION, SUM(AMOUNT) as Total_operaciones, ROUND(AVG(AMOUNT),2) as Promedio_operaciones 
FROM 
ORDERS
WHERE 
CREATED_AT > '2015-07-01' AND COUNTRY IN ('Portugal', 'Espana', 'Francia') AND AMOUNT BETWEEN 100 AND 1500
GROUP BY 
COUNTRY, STATUS
ORDER BY 
AVG(AMOUNT) DESC;


-- 3.2 Ejercicio 2
SELECT COUNTRY AS PAIS, COUNT(AMOUNT) AS TOTAL_OPRACIONES, MAX(AMOUNT) AS IMPORTE_MAXIMO, MIN(AMOUNT) AS IMPORTE_MINIMO, 
FROM ORDERS
WHERE STATUS != 'DELINQUENT' AND STATUS != 'CANCELLED' AND AMOUNT >= 100
GROUP BY COUNTRY
ORDER BY COUNT(AMOUNT) DESC
LIMIT 3;


-- 3.3 Ejercicio 3
SELECT 
    COUNTRY AS PAIS, M.NAME, 
    M.MERCHANT_ID, 
    SUM(O.AMOUNT) AS TOTAL_OPERACIONES, 
    ROUND(AVG(O.AMOUNT),2) AS PROMEDIO_DE_OPERACIONES, 
    COALESCE(SUM(R.AMOUNT), 0) AS TOTAL_DEVOLUCIONES, 
    COUNT(O.AMOUNT),
    CASE
        WHEN COALESCE(SUM(R.AMOUNT), 0) > 0 THEN 'Si'
        WHEN COALESCE(SUM(R.AMOUNT), 0) = 0 THEN 'No'
    END AS "HAY_DEVOLUCIONES"
FROM 
ORDERS AS O 
LEFT JOIN 
MERCHANTS AS M ON O.MERCHANT_ID = M.MERCHANT_ID
LEFT JOIN 
REFUNDS AS R ON O.ORDER_ID = R.ORDER_ID
WHERE 
COUNTRY IN('Marruecos', 'Italia', 'Espana', 'Portugal') 
GROUP BY 
COUNTRY, M.NAME, M.MERCHANT_ID
HAVING 
COUNT(O.AMOUNT) > 10;


-- 3.4 Ejercicio 4
CREATE OR REPLACE VIEW easy_loans_view AS
SELECT DISTINCT
O.ORDER_ID,
O.CREATED_AT,
O.STATUS,
O.AMOUNT,
O.COUNTRY,
M.MERCHANT_ID,
M.NAME,
COUNT(R.AMOUNT) OVER(PARTITION BY O.ORDER_ID) AS REFUNDS_PER_ORDER,
COALESCE(SUM(R.AMOUNT) OVER(PARTITION BY O.ORDER_ID),0) AS TOTAL_REFUNDS
FROM 
ORDERS AS O 
LEFT JOIN 
MERCHANTS AS M ON O.MERCHANT_ID = M.MERCHANT_ID
LEFT JOIN 
REFUNDS AS R ON O.ORDER_ID = R.ORDER_ID;

SELECT * FROM easy_loans_view;